# Generated by Django 2.0.2 on 2018-02-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20180216_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, to='images.Tag'),
        ),
    ]
