# Generated by Django 2.0.2 on 2018-02-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
    ]
