# Generated by Django 2.0.2 on 2018-03-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_remove_image_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
    ]
