# Generated by Django 2.0.2 on 2018-03-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_auto_20180309_1401'),
        ('images', '0012_image_bucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='tags',
        ),
        migrations.AddField(
            model_name='vote',
            name='labels',
            field=models.ManyToManyField(to='buckets.Label'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
