# Generated by Django 2.0.2 on 2018-03-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_auto_20180309_1401'),
        ('images', '0013_auto_20180312_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='bucket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='buckets.Bucket'),
            preserve_default=False,
        ),
    ]
