# Generated by Django 2.0.2 on 2018-03-13 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_vote_bucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='bucket',
        ),
    ]
