# Generated by Django 2.0.2 on 2018-03-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_remove_vote_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
