# Generated by Django 2.0.2 on 2018-03-23 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_auto_20180309_1401'),
        ('images', '0016_image_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='labels',
        ),
        migrations.AddField(
            model_name='vote',
            name='labels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='buckets.Label'),
        ),
    ]
