# Generated by Django 2.0.2 on 2018-03-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_auto_20180323_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='labels',
            new_name='label',
        ),
    ]
