# Generated by Django 2.0.2 on 2018-03-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_auto_20180323_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at']},
        ),
    ]
