# Generated by Django 2.0.2 on 2018-03-30 11:32

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0020_auto_20180329_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=images.models.upload_to),
        ),
    ]
