# Generated by Django 2.0.2 on 2018-04-05 09:29

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0021_auto_20180330_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(max_length=400, upload_to=images.models.upload_to),
        ),
    ]
