# Generated by Django 2.0.2 on 2018-04-05 09:35

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0023_auto_20180405_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(max_length=131, upload_to=images.models.upload_to),
        ),
    ]
