# Generated by Django 2.0.2 on 2018-04-19 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0010_auto_20180419_0954'),
        ('images', '0027_auto_20180419_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='bucket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buckets.Bucket'),
            preserve_default=False,
        ),
    ]
