# Generated by Django 2.0.2 on 2018-03-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='bucket',
            name='labels',
            field=models.ManyToManyField(to='buckets.Label'),
        ),
    ]
