# Generated by Django 2.0.2 on 2018-03-30 11:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buckets', '0003_auto_20180309_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='shared_users',
            field=models.ManyToManyField(related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
