# Generated by Django 2.0.2 on 2018-04-05 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0004_bucket_shared_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='shared_users',
            field=models.ManyToManyField(blank=True, related_name='shared_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
