# Generated by Django 2.0.2 on 2018-04-19 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0008_auto_20180419_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
